### PR TITLE
Update collaborating

### PR DESCRIPTION
**Pull request by helene-spring**

### CODE REVIEW

**Comment by helene-spring** [comment]
I think it's a good change personally

**Comment by CarienH** [comment]
I'm not sure I like the change; or have you updated it already?

**Review by CarienH — CHANGES_REQUESTED** [review]
Please say something nice

**Comment by helene-spring** [comment]
Ok I've made some changes, please take a look :)

**Review by CarienH — APPROVED** [review]
Wow, that's so nice!

**Pull request merged**
